language: python
env:
  - TESTING_ON_TRAVIS=1
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
install:
  - pip install -r requirements-test.txt
script: make test
after_success:
  - coveralls
